# General settings
name: 'm2m-model'      # Warning: 'debug' and 'test' are reserved name that have a special behavior
wandb: 'offline'             # online | offline | disabled
gpus: 1                     # Multi-gpu is not implemented on this branch
resume: null            # If resume, path to ckpt file from outputs directory in main directory
#test_only: /public/home/ustc_yangqs/molecular2molecular/outputs/2024-12-02/01-45-58-m2m-model/checkpoints/m2m-model/epoch=433.ckpt         # Use absolute path
test_only: null
check_val_every_n_epochs: 1
sample_every_val: 1

val_check_interval: null
samples_to_generate: 1       # We advise to set it to 2 x batch_size maximum
samples_to_save: 1
chains_to_save: 1
log_every_steps: 500
number_chain_steps: 1        # Number of frames in each gif

final_model_samples_to_generate: 512
final_model_samples_to_save: 512
final_model_chains_to_save: 512

evaluate_all_checkpoints: False