defaults:
    - _self_
    - general : general_default
    - model : discrete_condition
    - train : train_default
    - dataset : CHnmr

hydra:
  job:
    chdir: True
  run:
    dir: ../outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${general.name}




